### ISSUE TITLE
Detect missing installed sources

### ISSUE THREAD

**Issue by stevenengler** [pacak/cargo-show-asm#44]
When using `cargo asm` on the https://github.com/shadow/shadow respository with the `--rust` flag, I get the following panic:

```
$ cargo asm --rust -p shadow-shim-helper-rs "shadow_shim_helper_rs::emulated_time::EmulatedTime::saturating_add"
shadow_shim_helper_rs::emulated_time::EmulatedTime::saturating_add:
.Lfunc_begin11:
		// /tmp/shadow/src/lib/shadow-shim-helper-rs/src/emulated_time.rs : 99
		pub fn saturating_add(&self, duration: SimulationTime) -> EmulatedTime {
	.cfi_startproc
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 1500', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-show-asm-0.1.18/src/asm.rs:576:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:84:5
   3: cargo_show_asm::asm::dump_function
   4: cargo_asm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by pacak** [comment]
```
elakelaiset% cargo asm --rust -p shadow-shim-helper-rs "shadow_shim_helper_rs::emulated_time::EmulatedTime::saturating_add"
    Finished release [optimized] target(s) in 0.06s
shadow_shim_helper_rs::emulated_time::EmulatedTime::saturating_add:
.Lfunc_begin11:
                // /home/pacak/github/shadow/src/lib/shadow-shim-helper-rs/src/emulated_time.rs : 99
                pub fn saturating_add(&self, duration: SimulationTime) -> EmulatedTime {
        .cfi_startproc
                // /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/num/uint_macros.rs : 1501
                let (a, b) = intrinsics::add_with_overflow(self as $ActualT, rhs as $ActualT);
        mov rcx, qword ptr [rdi]
        lea rax, [rsi + rcx]
.Ltmp63:
                // /home/pacak/github/shadow/src/lib/shadow-shim-helper-rs/src/emulated_time.rs : 92
                EmulatedTime::from_c_emutime(self.0.checked_add(CSimulationTime::from(duration))?)
        cmp rax, -1
        mov rdx, -2
.Ltmp64:
                // /home/pacak/github/shadow/src/lib/shadow-shim-helper-rs/src/emulated_time.rs : 100
                match self.checked_add(duration) {
        cmove rax, rdx
.Ltmp65:
                // /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/num/uint_macros.rs : 1501
                let (a, b) = intrinsics::add_with_overflow(self as $ActualT, rhs as $ActualT);
        add rsi, rcx
.Ltmp66:
                // /home/pacak/github/shadow/src/lib/shadow-shim-helper-rs/src/emulated_time.rs : 100
                match self.checked_add(duration) {
        cmovb rax, rdx
                // /home/pacak/github/shadow/src/lib/shadow-shim-helper-rs/src/emulated_time.rs : 104
                }
        ret
.Ltmp67:
.Lfunc_end11:
        .size   shadow_shim_helper_rs::emulated_time::EmulatedTime::saturating_add, .Lfunc_end11-shadow_shim_helper_rs::emulated_time::EmulatedTime::saturating_add
        .cfi_endproc
```

I guess I need to know a bit more about your setup in order to be able to replicate the problem. Is it still crashing if you drop the `target` folder? Is it working at all on your machine? Do you have rust sources installed with whatever the rustup invocation is?

**Comment by pacak** [comment]
Also is it usual x86_64 Linux with no crosscompilation?

**Comment by stevenengler** [comment]
> Do you have rust sources installed with whatever the rustup invocation is?

This was it. It now works correctly after running `rustup component add rust-src`. Thanks for your help!

**Comment by pacak** [comment]
Ideally it should detect it and complain. Thank you for the report :)
